 default_platform(:ios)
 # 管理者用
 platform :ios do
   desc "appstore: Fetch Certificate and Profile"
   lane :appstore_fetch_cert_and_profile do
     api_key = app_store_connect_api_key(
       key_id: ENV["KEY_ID"],
       issuer_id: ENV["ISSUER_ID"],
       key_filepath: ENV["KEY_FILEPATH"],
       duration: 1200,
       in_house: false
     )

     match(
       api_key: api_key,
       type: "appstore",
       app_identifier: [ENV["APP_IDENTIFIER"]],
       force_for_new_devices: true
     )
   end
 end

 # 開発者用
 platform :ios do
   desc "readonly development: Fetch Certificate and Profiles"
   lane :readonly_development_fetch_cert_and_profile do
     match(
       type: "development",
       app_identifier: [ENV["APP_IDENTIFIER"]],
       readonly: false,
       force_for_new_devices: true
     )
   end
 end
