name: flutter_base
description: An extendable and modular Flutter template designed to accelerate app development. Providing a flexible foundation for a wide range of mobile applications.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  altive_lints: ^1.10.0
  custom_lint: ^0.6.4
  melos: ^3.4.0

flutter:
  uses-material-design: true
